### ISSUE TITLE
Some files contain multiple cities' policies

### ISSUE THREAD

**Issue by gregjd** [sunlightpolicy/opendata#31]
In the [opendatapoliciesdecoded](https://github.com/sunlightpolicy/opendata/tree/master/opendatapoliciesdecoded) directory, I noticed that the [Sacramento](https://github.com/sunlightpolicy/opendata/blob/master/opendatapoliciesdecoded/SacramentoXML.xml) file also includes Portland's policy.

In the [open data policies raw text](https://github.com/sunlightpolicy/opendata/tree/master/open%20data%20policies%20raw%20text) directory, I noticed this issue with several cities, including:

- [Charlotte](https://github.com/sunlightpolicy/opendata/blob/master/open%20data%20policies%20raw%20text/Charlotte.txt) (also has Las Vegas)
- [Chattanooga](https://github.com/sunlightpolicy/opendata/blob/master/open%20data%20policies%20raw%20text/Chattanooga.txt) (also has Tulsa)
- [Kansas City](https://github.com/sunlightpolicy/opendata/blob/master/open%20data%20policies%20raw%20text/Kansas%20City.txt) (also has Sacramento)
- [Las Vegas](https://github.com/sunlightpolicy/opendata/blob/master/open%20data%20policies%20raw%20text/Las%20Vegas.txt) (also has Seattle)
- [Sacramento](https://github.com/sunlightpolicy/opendata/blob/master/open%20data%20policies%20raw%20text/Sacramento.txt) (also has Portland)

and it may be the case for others (I didn't go through them all).

**Comment by shazooer** [comment]
We see the same thing. The scripts we used to separate the full "compendium" merged some of the policies together. I'll work to delete and separate policies that are merged.

**Comment by shazooer** [comment]
Fixed with commit https://github.com/sunlightpolicy/opendata/commit/556143c432180bcca731d8a5da67e9bd80946899

Thanks!
