### ISSUE TITLE
Data Quality

### ISSUE THREAD

**Issue by jalbertbowden** [sunlightpolicy/opendata#32]
cleaning some things up today, noticed that Montgomery County, MD, and Jackson, MS are listed in the file twice. Actually, it was Jackson, MI & Jackson, MS.
Both instances of Jackson throw 404s as well:
http://www.openjackson.org/
http://www.jacksonms.gov/CivicAlerts.aspx?AID=443

Each instance needs to be curated for data integrity:
 - Get rid of duplicates
 - Ensure policy URLs are not suffering from linkrot
 - Ensure data is correct

**Comment by shazooer** [comment]
Removed Duplicates and repeating text within. 
URLs still need to be verified.
